### ISSUE TITLE
qsign似乎只在单核工作 

### ISSUE THREAD

**Issue by S-TE11A** [MrXiaoM/qsign#12]
qsign似乎只在单核工作 我的服务器单核性能比较差，qsign运作的时候单核占用非常高，其他的核心占用都是0，请问有没有什么好的解决方案？
![{VFS_HT1) P6B5M0PMW}Q 1](https://github.com/MrXiaoM/qsign/assets/20638533/e2465787-46e5-4140-b908-b9d75fbfaef3)

**Comment by MrXiaoM** [comment]
没有。
