### ISSUE TITLE
签名服务开启后仍然报错45

### ISSUE THREAD

**Issue by the-lazy-me** [MrXiaoM/qsign#13]
![image](https://github.com/MrXiaoM/qsign/assets/52873503/5f101844-2be4-479c-bdfc-6514d8890b2b)
![image](https://github.com/MrXiaoM/qsign/assets/52873503/6aeae48e-7b98-4e49-9b3e-c536d61c08be)

**Comment by cheng77970** [comment]
+1，我也是，协议是8.9.58的安卓平板，签名已经在工作了但是还是45

**Comment by hunzi2636** [comment]
我也是，一样的报错(┬┬﹏┬┬)
