### ISSUE TITLE
mira启动报错

### ISSUE THREAD

**Issue by smilecat2788** [MrXiaoM/qsign#14]
第一次运行没啥问题，登录上去了，然后我看日志太多就ctrl c关闭了改了日志配置文件，再次开启mira一切正常，直到登录账号的时候报错
java: /home/zhkl0228/git/unicorn/qemu/memory.c:1329: memory_region_del_subregion_aarch64: Assertion `subregion->container == mr' failed.
Aborted (core dumped)
此后在怎么重启都没有用了，一直是这个报错
另外在第一次关闭时出现了以下提示，在未安装此插件时没看到过
2023-09-16` 16:40:28 V/Bot.483392198: Event: BotOfflineEvent.Active(bot=Bot(483392198), cause=null, reconnect=false)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff0fc2e8a2b, pid=2288823, tid=2289012
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libunicorn.so+0xe8a2b]  tb_find_slow_aarch64+0x1ba
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/mira/core.2288823)
#
# An error report file with more information is saved as:
# /home/mira/hs_err_pid2288823.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core `dumped)
使用环境是ubuntu22.04，使用的协议版本为8.9.73

**Comment by smilecat2788** [comment]
[hs_err_pid2288823.log](https://github.com/MrXiaoM/qsign/files/12640244/hs_err_pid2288823.log)
错误文件在这里

**Comment by MrXiaoM** [comment]
unicorn 在 native 层面的报错，不是我能解决的范畴

**Comment by smilecat2788** [comment]
啊，那我看看升级一下Java能不能解决吧，只有这个签名支持73版本，别的版本都报版本太低了
