### ISSUE TITLE
适配新版本签名

### ISSUE THREAD

**Issue by suzuka-suzuka** [MrXiaoM/qsign#19]
求适配8.9.80版本的签名

**Comment by MrXiaoM** [comment]
已更新

**Comment by CaiJingLong** [comment]
> 已更新

我其实很想知道，这个每个版本的 android_phone.json 文件是如何生成的

**Comment by MrXiaoM** [comment]
> 我其实很想知道，这个每个版本的 android_phone.json 文件是如何生成的

信息都在apk里，反编译获得
