### ISSUE TITLE
java.lang.IllegalStateException: Mutex is not locked

### ISSUE THREAD

**Issue by qingshanlanshan** [MrXiaoM/qsign#2]
<img width="1086" alt="image" src="https://github.com/MrXiaoM/qsign/assets/68636377/cefabab0-9807-48ba-8343-fafaec473a28">

如图，使用最新的release版本，系统为ubuntu20，正常启动mcl后就会出现，mirai仍能正常运行，有时mirai会无法输入（不确定是否与本bug有关）

另外，如
2023-07-27 09:57:15 I/stdout: clock_gettime clk_id=0, tp=unidbg@0xbfffd308, offset=1690423035119000000, tv_sec=1690423035, tv_nsec=119000000
之类的消息是否方便放到debug输出？

感谢！

**Comment by MrXiaoM** [comment]
尝试使用最新构建
https://github.com/MrXiaoM/qsign/suites/14617976867/artifacts/828716712

**Comment by qingshanlanshan** [comment]
> 尝试使用最新构建 https://github.com/MrXiaoM/qsign/suites/14617976867/artifacts/828716712

<img width="1079" alt="image" src="https://github.com/MrXiaoM/qsign/assets/68636377/0b82ee7a-3402-4fd8-bfa7-ac8dac65bc7c">

请问这个是和release1.05是一样的吗？有差不多的报错，但行号不一样

我应该使用1.04吗？

**Comment by MrXiaoM** [comment]
换 1.0.4 吧，估计 unidbg-fetch-qsign 1.1.7 加的新机制有问题。我也暂时没时间排查。
新的构建合并了 unidbg-fetch-qsign `fix #164` 那个提交，不行就代表没修好。

**Comment by qingshanlanshan** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/2434
对kt不熟，但看起来应该和这个问题有关？不知道能不能帮到
