### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Tamamoimoto** [MrXiaoM/qsign#4]
[93m2023-08-12 21:08:16 W/MiraiNative: Linked class io.ktor.client.engine.okhttp.OkHttp in onebot-mirai-0.3.4-fix.jar but plugin not depend on it.[0m[m
[93m2023-08-12 21:08:16 W/MiraiNative: Class loading logic may change in feature.[0m[m
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast

版本：Mirai console 2.15.0+qsign-1.0.4.mirai2
系统：Linux armbian 5.15.58-flippy-75+o 148 SMP PREEMPT Sat Jul 30 11:32:27 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
删除onebot-mirai-0.3.4-fix.jar后正常启动

**Comment by MrXiaoM** [comment]
onebot mirai 已经年久失修了，并且这不是我的插件的问题
